# Generated by Django 3.0.7 on 2020-06-03 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ariticle',
            new_name='Article',
        ),
    ]
